language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t rickchiu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rickchiu/react-test npm test

after_success:
  - docker build -t rickchiu/multi-client ./client
  - docker build -t rickchiu/multi-nginx ./nginx
  - docker build -t rickchiu/multi-server ./server
  - docker build -t rickchiu/multi-worker ./worker

